apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheba-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sheba-client
  template:
    metadata:
      labels:
        app: sheba-client
    spec:
      containers:
      - name: sheba-client
        image: nayem9b/sheba:latest

---

apiVersion: v1
kind: Service
metadata:
  name: sheba-client
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: sheba-client
  type: LoadBalancer