apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheba-client
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: sheba-client
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: sheba-client
    spec:
      containers:
      - name: sheba-client
        # Run this image
        image: nayem9b/sheba:latest